apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: my_nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
